### PR TITLE
Social Media App: Milestone 1 (docs)

### PR DESCRIPTION
**Pull request by ElijahTobs**
In this PR, I:

- Changed the ruby version from 2.7.0 to 2.7.1
- installed PostgreSQL and updated the database.yml file to include username and password for PostgreSQL authentication
- added a docs file and added a .png file that contains the ERD of this project.

I humbly request a review.

### CODE REVIEW

**Review by maelfosso — CHANGES_REQUESTED** [review]
# Changes required :red_circle: 

Hello,

Thank you for the job done so far.
However, there are some missing requirements

1. As indicated [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone1/status.png), the `Friendship` table must have a field **status** or **confirmed**

2. Kindly add a **ID** field as primary key into the `Like` table. Also, the `post_id` is not the primary key of the `Like` table. Fix that, please.

3. Kindly add `ID` as primary key into the `Comment` table.

Once all the changes applied, submit a new code review request
Thanks

Mael FOSSO

**Review by maelfosso — CHANGES_REQUESTED** [review]
# Changes required :red_circle: 

Hello,

Thank you for applying the suggested changes
However, there are some missing requirements

1. The `post_id` field in the `Like` table should be labelled as Foreign Key because it was it is

2. You forgot **ID** into the `Like` table

Kindly make the changes and submit a new code review request
Thanks

Mael FOSSO

**Review by mosesogwo — APPROVED** [review]
**Hello! :wave: Good work on the requested change :+1: Your milestone is approved**

Only, take note of this. For your posts and users table, will you have the primary keys as _post\_id_ and _user\_id_ or simply _id_?

Also remember to setup your linters properly and make sure the linter check reports appear on future pull requests.

**Good luck in your project :stars:**

### Status: Approved :heavy_check_mark:

**Comment by ElijahTobs** [comment]
Thanks, @mosesogwo primary keys post_id and user_id has been changed to id

**Pull request merged**
